# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Andrew Po≈æenel
    url: mailto:andrew.pozenel@tutanota.com
    about: Please ask Scoop related questions here.
